### ISSUE TITLE
[bug] `SignedTransaction` and `SignedTransactionCandidate` should not implement `Decode` / `Deserialize` in `no_std`

### ISSUE THREAD

**Issue by Arjentix** [hyperledger-iroha/iroha#3607]
Originally posted by @mversic [here](https://github.com/hyperledger/iroha/pull/3588#discussion_r1228115374)

# How to test

Honestly I don't think it's worth spending time on tests like this.

## Before changes

Currently it's possible to create a Rust package which will link to `iroha_data_model` with `default-features = false` enabled. That will disable `std` feature. After that you should be able to decode / deserialize `SignedTransaction` with wrong signatures, because they won't be checked at `no_std`

## After changes

You should get a compile error if you try to decode / deserialize `SignedTransaction` from `no_std` environment.

**Comment by DCNick3** [comment]
This is not possible to implement as-is because it breaks the validator (see https://github.com/hyperledger/iroha/pull/3686#issuecomment-1628935427, TLDR: validator decodes `SignedTransaction` for ffi)

Even if it was implemented, it's additionally harder to make it a compile-time error, as the `versioned!` macro used on the `SignedTransaction` requires `Deserialize` and `Decode`, reducing the utility.

The only really actionable item is documenting it clearly I guess
